### ISSUE TITLE
Consume without azure function

### ISSUE THREAD

**Issue by FBurner** [Azure-Samples/event-grid-node-publish-consume-events#10]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> none just a question

How to consume eventgrid without azure function?

**Comment by lmazuel** [comment]
Hello, I believe this is the answer to your question:
https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/eventgrid/eventgrid

Thanks!
